### PR TITLE
MumbleGuiClient: [feature] Minimal Microphone Volume Level

### PR DESCRIPTION
**Pull request by Meetsch**
Send voice only when the microphone volume level is above a threshold (in percent of microphone volume). Therefore the voice will not be sent to murmur when the microphone is nearly silent. There's a hold time of 500ms (the duration of silence before transmission stops).

### CODE REVIEW

**Comment by Meetsch** [comment]
Solution to the https://github.com/martindevans/MumbleSharp/issues/33

**Comment by martindevans** [comment]
There are a couple of issues with this (I faced exactly the same problem with the Voice detector which shipped for a few months in Dissonance before we replaced it).

 - Activation threshold is too high. When you are currently _not_ transmitting you want to use a lower threshold so it's easier to detect speech.
 - Hold time doesn't look quite right, you want it so that you don't stop transmitting unless you detect N consecutive frames of non-speech.

The general idea should be that you err very much on the side of caution, so you classify something as speech as soon as possible. You also don't want to start and stop too much (that sounds annoying) so you want the hold time to cover pauses in speech.

**Comment by Meetsch** [comment]
Hi,

According to your suggestions, I refactored the code to:
1. Use a lower threshold when you are currently not transmitting (different noise and voice detection thresholds)
2. Have different hold time when only noise is detected, and switch to a longer hold-time as soon as voice is detected.
3. The volume detection is now continuous to ensure proper hold-time.
4. When voice is detected the hold-time is now 1s.

I kept the code as simple as possible because this is a sample app, but now with a simple voice detection feature as one would expect.

Kind regards,

Michel

**Comment by martindevans** [comment]
Hi, Sorry this has taken me so long to review :(

Could you factor out the voice detector logic into a separate class? It's likely we'll want to replace the voice detector with something more robust in the future, so it'd be convenient to have it easily replaceable.

**Comment by Meetsch** [comment]
Here is the MumbleGuiClient voice detector in a separate class BasicVoiceDetector : IVoiceDetector

**Comment by martindevans** [comment]
Thanks for the PR :)

Sorry this took so long to review again!

**Pull request merged**
