### PR TITLE
Feature: Channel Administration & speaking in multiple channels + minor fixes

### PR DESCRIPTION
**Pull request by Meetsch**
(feature) Added support for Permissions, channel Create/Move/Remove.
(feature) Send voice to speech targets.
(feature) Support for all MumbleProto Packet types. Also includes full documentation.
(fix) Reject message deserialization was wrong.
(fix) Code was not matching mumble logic which disallows being deaf without being also muted.
(fix) Avoid MumbleGuiClient UI freezing (smart usage of Thread.Yield() and Thread.Spleep(1)).
(refactor) use DateTime.UtcNow instead of DateTime.Now for performance (see http://benhall.io/net-performance-tip-benchmarking/).

### CODE REVIEW

**Comment by martindevans** [comment]
Thanks for another great PR! I'll try to review this soon :)

**Comment by Meetsch** [comment]
Hi Martin, feel free to ask me if things are unclear/uncertain.

**Comment by martindevans** [comment]
Hey, thanks for the nudge. I'll try to make time to review this over the weekend :)

**Comment by martindevans** [comment]
As usual thanks for all the excellent work @Meetsch!

**Pull request merged**
